version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A celery_app.celery_app worker --loglevel=info
    volumes:
      - ../:/app
      - ../data:/app/data
    depends_on:
      - redis
    environment:
      - TZ=Europe/Warsaw
  celery_beat:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A celery_app.celery_app beat --loglevel=info
    volumes:
      - ../:/app
      - ../data:/app/data
    depends_on:
      - redis
    environment:
      - TZ=Europe/Warsaw